use mssqlupc
go
CREATE TABLE CATEGORIA
(
IDCATEGORIA CHAR(1),
NOMBRE VARCHAR(80)
)
GO
CREATE TABLE CLIENTE (
IDCLIENTE CHAR(3),
NOMBRES VARCHAR(70),
APELLIDOS VARCHAR(100),
DNI CHAR(8),
DIRECCION VARCHAR(20),
CORREO VARCHAR(100)
)
GO
CREATE TABLE PRODUCTO
(
IDPRODUCTO CHAR(4),
NOMBRE VARCHAR(200),
IDCATEGORIA CHAR(1),
PRECIO FLOAT,
STOCK FLOAT
)
GO
CREATE TABLE PEDIDO
(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
IDPEDIDO AS 'PE' + RIGHT('0' + CAST(ID AS VARCHAR(4)), 4) PERSISTED,
IDCLIENTE CHAR(3),
TOTALVENTA FLOAT,
REALIZADO BIT
)
GO
CREATE TABLE PEDIDODETALLE
(
IDPEDIDODETALLE INT IDENTITY(1,1) PRIMARY KEY,
IDPEDIDO VARCHAR(4),
IDPRODUCTO CHAR(4),
CANTIDAD DECIMAL(10,2),
PRECIO DECIMAL(10,2),
TOTAL AS ROUND(CANTIDAD*PRECIO,2) PERSISTED 
)
GO

CREATE TABLE CLIENTE (
IDCLIENTE CHAR(3),
NOMBRES VARCHAR(70),
APELLIDOS VARCHAR(100),
DNI CHAR(8),
DIRECCION VARCHAR(20),
CORREO VARCHAR(100),
CONTRASENA VARCHAR(50)
)
GO

ALTER PROCEDURE REGISTRAR_PEDIDO
(
@IDPEDIDO VARCHAR(4),
@IDCLIENTE CHAR(3),
@TOTALVENTA FLOAT,
@REALIZADO BIT,
@IDPRODUCTO CHAR(4),
@CANTIDAD FLOAT,
@PRECIO FLOAT
)
AS
IF EXISTS(SELECT 1 FROM PEDIDO WHERE IDCLIENTE = @IDCLIENTE AND REALIZADO = 0)
BEGIN
	UPDATE PEDIDO SET TOTALVENTA = @TOTALVENTA WHERE IDCLIENTE = @IDCLIENTE
END
ELSE
BEGIN
	INSERT INTO PEDIDO (IDCLIENTE, TOTALVENTA, REALIZADO)
	VALUES (@IDCLIENTE,@TOTALVENTA,@REALIZADO)
	SET @IDPEDIDO = (SELECT IDPEDIDO FROM PEDIDO WHERE IDCLIENTE = @IDCLIENTE AND REALIZADO = 0)
END

IF EXISTS(SELECT 1 FROM PEDIDODETALLE WHERE IDPEDIDO = @IDPEDIDO AND IDPRODUCTO = @IDPRODUCTO)
BEGIN
	UPDATE PEDIDODETALLE SET CANTIDAD = CANTIDAD + @CANTIDAD, PRECIO = @PRECIO  WHERE IDPEDIDO = @IDPEDIDO AND IDPRODUCTO = @IDPRODUCTO
END
ELSE
BEGIN
	INSERT INTO PEDIDODETALLE (IDPEDIDO, IDPRODUCTO, CANTIDAD, PRECIO) VALUES (@IDPEDIDO, @IDPRODUCTO, @CANTIDAD, @PRECIO)
END

SELECT @IDPEDIDO
GO

INSERT INTO CATEGORIA (IDCATEGORIA, NOMBRE) VALUES ('V', 'VERDURAS')
INSERT INTO CATEGORIA (IDCATEGORIA, NOMBRE) VALUES ('M', 'ALIMENTOS MARINOS')
INSERT INTO CATEGORIA (IDCATEGORIA, NOMBRE) VALUES ('F', 'FRUTAS')
INSERT INTO CATEGORIA (IDCATEGORIA, NOMBRE) VALUES ('L', 'LACTEOS')

INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE, IDCATEGORIA, PRECIO, STOCK)
VALUES
    ('P001', 'TOMATE', 'V', 4.5, 100),
    ('P002', 'CEBOLLA', 'V', 3.9, 50),
    ('P003', 'LECHUGA', 'V', 5.4, 30),
	('P004', 'API', 'V', 2.3, 30),
	('P005', 'ALCACHOFA', 'V', 7.7, 50),
	('P006', 'LECHE SIN LACTOSA PASTEURIZADA', 'L', 19.8, 50);

GO
INSERT INTO CLIENTE (IDCLIENTE, NOMBRES, APELLIDOS, DNI, DIRECCION, CORREO, CONTRASENA) VALUES
('C01', 'GIANFRANCO','CARRASCO','46056544','AV LIMA 1232','GIANFRANCO@GMAIL.COM','1234')

GO
SELECT * FROM CLIENTE
SELECT * FROM PEDIDO
SELECT * FROM PEDIDODETALLE
SELECT * FROM CATEGORIA
SELECT * FROM PRODUCTO

DELETE FROM PEDIDO
DELETE FROM PEDIDODETALLE


--IF EXISTS(SELECT 1 FROM PEDIDODETALLE WHERE IDPEDIDO = @IDPEDIDO)
--BEGIN
--	IF EXISTS(SELECT 1 FROM PEDIDODETALLE WHERE IDPEDIDO = @IDPEDIDO AND IDPRODUCTO = @IDPRODUCTO)
--	BEGIN
--		UPDATE PEDIDODETALLE SET CANTIDAD = CANTIDAD + @CANTIDAD, PRECIO = @PRECIO  WHERE IDPEDIDO = @IDPEDIDO AND IDPRODUCTO = @IDPRODUCTO
--	END
--	ELSE
--	BEGIN
--		INSERT INTO PEDIDODETALLE (IDPEDIDO, IDPRODUCTO, CANTIDAD, PRECIO) VALUES (@IDPEDIDO, @IDPRODUCTO, @CANTIDAD, @PRECIO)
--	END
--END
--ELSE
--BEGIN
--	INSERT INTO PEDIDODETALLE (IDPEDIDO, IDPRODUCTO, CANTIDAD, PRECIO) VALUES (@IDPEDIDO, @IDPRODUCTO, @CANTIDAD, @PRECIO)
--END