use mssqlupc
go
CREATE TABLE CATEGORIA
(
IDCATEGORIA CHAR(1),
NOMBRE VARCHAR(80)
)
GO
CREATE TABLE PRODUCTO
(
IDPRODUCTO CHAR(4),
NOMBRE VARCHAR(200),
IDCATEGORIA CHAR(1),
PRECIO FLOAT,
STOCK FLOAT,
RUTAIMAGEN VARCHAR(200)
)
GO
SELECT RIGHT('00' + CONVERT(VARCHAR(2), 1), 2)
FROM Mytable

CREATE TABLE PEDIDO
(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
IDPEDIDO AS 'PE' + RIGHT('00' + CONVERT(VARCHAR(2), ID), 2) PERSISTED,
IDCLIENTE CHAR(3),
TOTALVENTA FLOAT,
REALIZADO BIT
)
GO
CREATE TABLE PEDIDODETALLE
(
IDPEDIDODETALLE INT IDENTITY(1,1) PRIMARY KEY,
IDPEDIDO VARCHAR(4),
IDPRODUCTO CHAR(4),
CANTIDAD DECIMAL(10,2),
PRECIO DECIMAL(10,2),
TOTAL AS ROUND(CANTIDAD*PRECIO,2) PERSISTED 
)
GO

CREATE TABLE CLIENTE (
IDCLIENTE CHAR(3),
NOMBRES VARCHAR(70),
APELLIDOS VARCHAR(100),
DNI CHAR(8),
DIRECCION VARCHAR(20),
CORREO VARCHAR(100),
CONTRASENA VARCHAR(50),
TELEFONO VARCHAR(30)
)
GO

ALTER PROCEDURE REGISTRAR_PEDIDO
(
@IDPEDIDO VARCHAR(4),
@IDCLIENTE CHAR(3),
@TOTALVENTA FLOAT,
@REALIZADO BIT,
@IDPRODUCTO CHAR(4),
@CANTIDAD FLOAT,
@PRECIO FLOAT
)
AS
IF EXISTS(SELECT 1 FROM PEDIDO WHERE IDCLIENTE = @IDCLIENTE AND REALIZADO = 0)
BEGIN
	UPDATE PEDIDO SET TOTALVENTA = @TOTALVENTA WHERE IDCLIENTE = @IDCLIENTE
END
ELSE
BEGIN
	INSERT INTO PEDIDO (IDCLIENTE, TOTALVENTA, REALIZADO)
	VALUES (@IDCLIENTE,@TOTALVENTA,@REALIZADO)
	SET @IDPEDIDO = (SELECT IDPEDIDO FROM PEDIDO WHERE IDCLIENTE = @IDCLIENTE AND REALIZADO = 0)
END

IF EXISTS(SELECT 1 FROM PEDIDODETALLE WHERE IDPEDIDO = @IDPEDIDO AND IDPRODUCTO = @IDPRODUCTO)
BEGIN
	UPDATE PEDIDODETALLE SET CANTIDAD = CANTIDAD + @CANTIDAD, PRECIO = @PRECIO  WHERE IDPEDIDO = @IDPEDIDO AND IDPRODUCTO = @IDPRODUCTO
END
ELSE
BEGIN
	INSERT INTO PEDIDODETALLE (IDPEDIDO, IDPRODUCTO, CANTIDAD, PRECIO) VALUES (@IDPEDIDO, @IDPRODUCTO, @CANTIDAD, @PRECIO)
END

SELECT @IDPEDIDO
GO

CREATE PROCEDURE VALIDAR_CLIENTE
(
@CORREO VARCHAR(80), 
@CONTRASENA VARCHAR(80)
)
AS
SELECT A.IDCLIENTE, A.NOMBRES, A.APELLIDOS, A.DNI, A.DIRECCION, A.CORREO, A.TELEFONO, ISNULL(A.IDPEDIDO,'') AS IDPEDIDO FROM (
SELECT C.IDCLIENTE, C.NOMBRES, C.APELLIDOS, C.DNI, C.DIRECCION, C.CORREO, C.CONTRASENA, C.TELEFONO
, (
SELECT P.IDPEDIDO FROM PEDIDO P WHERE P.IDCLIENTE = C.IDCLIENTE AND P.REALIZADO = 0
) AS IDPEDIDO 
FROM CLIENTE C
WHERE UPPER(CORREO) = UPPER(@CORREO) AND UPPER(C.CONTRASENA) = UPPER(@CONTRASENA) 
) A
GO

INSERT INTO CATEGORIA (IDCATEGORIA, NOMBRE) VALUES ('V', 'VERDURAS')
INSERT INTO CATEGORIA (IDCATEGORIA, NOMBRE) VALUES ('M', 'ALIMENTOS MARINOS')
INSERT INTO CATEGORIA (IDCATEGORIA, NOMBRE) VALUES ('F', 'FRUTAS')
INSERT INTO CATEGORIA (IDCATEGORIA, NOMBRE) VALUES ('L', 'LACTEOS')

INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE, IDCATEGORIA, PRECIO, STOCK, RUTAIMAGEN)
VALUES
    ('P001', 'TOMATE', 'V', 4.5, 100,'../../assets/img/featured/feature-3.jpg'),
    ('P002', 'SANDÍA', 'F', 3.9, 50, '../../assets/img/featured/feature-4.jpg'),
    ('P003', 'ARÁNDANOS', 'F', 5.4, 30, '../../assets/img/featured/feature-5.jpg'),
	('P004', 'MANGO', 'F', 2.3, 30, '../../assets/img/featured/feature-7.jpg'),
	('P005', 'MANZANA', 'F', 7.7, 50, '../../assets/img/featured/feature-8.jpg'),
	('P006', 'LECHE SIN LACTOSA PASTEURIZADA', 'L', 19.8, 50, '../../assets/img/featured/feature-9.jpg'),
	('P007', 'CARNE PARA GUISO', 'M', 3.5, 200,'../../assets/img/featured/feature-1.jpg')

GO
INSERT INTO CLIENTE (IDCLIENTE, NOMBRES, APELLIDOS, DNI, DIRECCION, CORREO, CONTRASENA) VALUES
('C01', 'GIANFRANCO','CARRASCO','46056544','AV LIMA 1232','GIANFRANCO@GMAIL.COM','1234')

GO
SELECT * FROM CLIENTE
SELECT * FROM PEDIDO
SELECT * FROM PEDIDODETALLE
SELECT * FROM CATEGORIA
SELECT * FROM PRODUCTO

DELETE FROM PEDIDO
DELETE FROM PEDIDODETALLE


GO
SELECT TOP 4 * FROM PRODUCTO ORDER BY NEWID()